spring:
  application:
    name: personal-account-system
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 20
      max-wait: 60000
      initial-size: 1
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: Spark
    password: Spark

server:
  port: 8090
  tomcat:
    max-threads: 200
  servlet:
    context-path: /personal-account-system
    session:
      timeout: 30m